import os
import json
import re
from openai import OpenAI

def get_client() -> OpenAI:
    api_key = os.environ.get("MINIMAX_API_KEY", "").strip()
    if not api_key:
        raise ValueError("MINIMAX_API_KEY is not set.")
    return OpenAI(api_key=api_key, base_url="https://api.minimaxi.chat/v1")

def _parse_json_safely(text: str) -> dict:
    # Strip out '<think>...</think>' blocks generated by reasoning models
    cleaned = re.sub(r'<think>[\s\S]*?</think>', '', text)
    cleaned = re.sub(r'```json\n?', '', cleaned)
    cleaned = re.sub(r'```', '', cleaned).strip()
    try:
        return json.loads(cleaned)
    except Exception as e:
        print(f"JSON Parsing Error: {e}\nRaw output: {text}")
        return {}

def extract_form_and_prefill(form_markdown: str, context_markdown: str = "") -> dict:
    """Mode A: Extracts form schema and maps context info if available."""
    client = get_client()
    system_prompt = (
        "You are an expert form filling assistant.\n"
        "1. Extract all logical form fields from the provided 'Form Layout'.\n"
        "2. If 'Context Data' is provided, intelligently map the context into the identified form fields.\n"
        "3. Output ONLY valid JSON where keys are the field names and values are the extracted value (or empty string if missing).\n"
    )
    
    user_prompt = f"--- Form Layout ---\n{form_markdown}\n"
    if context_markdown:
        user_prompt += f"\n--- Context Data ---\n{context_markdown}\n"
        
    response = client.chat.completions.create(
        model="MiniMax-M2.7",
        messages=[{"role": "system", "content": system_prompt}, {"role": "user", "content": user_prompt}],
        temperature=1.0, top_p=0.95
    )
    return _parse_json_safely(response.choices[0].message.content)

def validate_field_input(field_name: str, raw_input: str) -> str:
    """Mode B: Canonicalize short manual inputs (formatting, capitalization, etc)."""
    client = get_client()
    system_prompt = (
        "You are a strict data validation format tool. "
        "Fix capitalization, spelling, and standard formatting for the user's manual input for the specific form field. "
        "Output ONLY the corrected text string directly. No explanations."
    )
    user_prompt = f"Field: {field_name}\nRaw Input: {raw_input}"
    
    response = client.chat.completions.create(
        model="MiniMax-M2.7",
        messages=[{"role": "system", "content": system_prompt}, {"role": "user", "content": user_prompt}],
        temperature=0.1, top_p=0.95
    )
    return response.choices[0].message.content.strip()

def chat_and_update_fields_stream(chat_history: list, current_state: dict) -> tuple:
    """Mode C: Process user chat and stream dynamically to UI."""
    client = get_client()
    missing_fields = [k for k, v in current_state.items() if not v["value"]]
    
    system_prompt = (
        "You are a conversational form-filling assistant answering the user.\n"
        f"The user needs to fill out these missing fields: {missing_fields}\n"
        "Review the conversation history and naturally ask the user for missing info, or answer their questions.\n"
        "\n"
        "SPECIAL PROTOCOLS:\n"
        "1. SKIPPING FIELDS: If a user explicitly asks to leave a field blank or skip it, map that field in your JSON as '[[BLANK]]'.\n"
        "2. READY TO GENERATE: If ALL fields are now either filled or marked as '[[BLANK]]', include a top-level key 'READY_TO_GENERATE': true in your UPDATES JSON. Otherwise set it to false.\n"
        "\n"
        "You MUST output exactly two distinct blocks in this exact format:\n\n"
        "REPLY:\n<your conversational response to the user>\n"
        "UPDATES:\n```json\n<JSON dict including 'READY_TO_GENERATE' and any field updates logic. Return {'READY_TO_GENERATE': false} if no field updates.>\n```"
    )
    
    messages = [{"role": "system", "content": system_prompt}]
    for msg in chat_history:
        messages.append({"role": msg["role"], "content": msg["content"]})
        
    response = client.chat.completions.create(
        model="MiniMax-M2.7",
        messages=messages,
        temperature=1.0, top_p=0.95,
        stream=True
    )
    
    result_ref = {"updates_json": {}}
    
    def generator():
        buffer = ""
        in_think = False
        in_reply = False
        in_updates = False
        updates_buffer = ""
        last_found_fields = set()
        
        for chunk in response:
            if not chunk.choices or not chunk.choices[0].delta.content:
                continue
                
            token = chunk.choices[0].delta.content
            buffer += token
            
            if not in_think and "<think>" in buffer:
                in_think = True
                buffer = buffer.split("<think>")[-1]
                continue
                
            if in_think:
                if "</think>" in buffer:
                    in_think = False
                    buffer = buffer.split("</think>")[-1]
                continue
                
            if in_updates:
                updates_buffer += token
                # Live extract fields from buffer
                # Look for "key": "value" patterns
                # This regex catches simple string values.
                matches = re.findall(r'"([^"]+)":\s*"([^"]*)"', updates_buffer)
                for k, v in matches:
                    if k not in last_found_fields and k != "READY_TO_GENERATE":
                        yield ("FIELD_UPDATE", k, v)
                        last_found_fields.add(k)
                continue
                
            if "REPLY:" in buffer:
                in_reply = True
                buffer = buffer.replace("REPLY:", "").lstrip()
                
            if "UPDATES:" in buffer:
                in_updates = True
                parts = buffer.split("UPDATES:")
                if parts[0]:
                    yield ("TEXT", parts[0])
                updates_buffer += parts[1] if len(parts) > 1 else ""
                buffer = ""
                continue
                
            if in_reply:
                if len(buffer) > 15:
                    safe_len = len(buffer) - 10
                    yield ("TEXT", buffer[:safe_len])
                    buffer = buffer[safe_len:]
                    
        if buffer and not in_updates and not in_think:
            yield ("TEXT", buffer)
            
        if updates_buffer:
            result_ref["updates_json"] = _parse_json_safely(updates_buffer)
            # Final check for any missed fields (like non-string values or trailing)
            final_json = result_ref["updates_json"]
            for k, v in final_json.items():
                if k not in last_found_fields and k != "READY_TO_GENERATE":
                     yield ("FIELD_UPDATE", k, v)
            
    return generator(), result_ref
